language: node_js
node_js:
  #  - 0.8
  - 0.10
  - 0.12
  - 4
  - 6
  - 8
  - 10
  - 12
  - 14
os:
  - linux
  - osx
  - windows
script:
  - npm install cross-env@2
  - ./node_modules/.bin/cross-env NODE_OPTIONS=--max_old_space_size=2048 CI=true ./node_modules/.bin/mocha-compat test/spec/**/*.test.js --no-timeouts
