language: node_js
node_js:
  - lts/*
os:
  - linux
  - osx
  - windows
script:
  - npm install node-version-use -g
  - nvu engines ./node_modules/.bin/mocha-compat test/spec/**/*.test.js --no-timeouts
