#!/usr/bin/env node

const meow = require('meow');
const nvs = require('.');

const cli = meow(
  `
Usage
  $ nvs [version ...] -- <command>
Examples
  $ nvs 0.10 4 6 14 -- npm test
  `,
  {
    flags: {
      help: {
        alias: 'h',
      },
      version: {
        alias: 'v',
      },
      '--': true,
    },
  }
);

var command = cli.flags['--'];
if (!command || command.length === 0) return console.log('Error: command missing');

nvs(cli.input, command, function (err) {
  if (err) {
    console.log(err.message);
    return process.exit(err.exitCode || -1);
  }
  process.exit(0);
});
