name: CI
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Node.js ${{ matrix.node-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['lts/Jod']
        os: [ubuntu-latest, windows-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: git config --global user.name "Github Actions"
      - run: git config --global user.email "actions@users.noreply.github.com"
      - run: npm install rimraf -g
      - run: rimraf $HOME/.im
      - run: npm install ts-dev-stack node-version-use -g --force
      - run: npm install depcheck -g
      - run: depcheck
      - run: npm ci
      - run: npm run docs
      - run: npm run build
      - run: npm run test
      - run: npm run test:engines
